version: '3.8'

services:
  quiz-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]
